[2025-04-06T10:29:16.355+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:16.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:29:16.466+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:29:16.465+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:18.618+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:29:18.574+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:29:18.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:18.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.522 seconds
[2025-04-06T10:29:49.248+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:49.254+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:29:49.271+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:29:49.270+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:49.650+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:29:49.646+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:29:49.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:29:49.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.503 seconds
[2025-04-06T10:30:20.029+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:20.033+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:30:20.040+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:30:20.037+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:20.231+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:30:20.229+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:30:20.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:20.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.254 seconds
[2025-04-06T10:30:50.406+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:50.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:30:50.412+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:30:50.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:50.579+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:30:50.573+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:30:50.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:30:50.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.240 seconds
[2025-04-06T10:31:21.035+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:21.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:31:21.058+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:31:21.057+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:22.008+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:31:21.996+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:31:22.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:22.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.129 seconds
[2025-04-06T10:31:53.076+0000] {processor.py:157} INFO - Started process (PID=35) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:53.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:31:53.109+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:31:53.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:53.545+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:31:53.532+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:31:53.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:31:53.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.604 seconds
[2025-04-06T10:32:24.246+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:24.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:32:24.266+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:32:24.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:24.552+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:32:24.548+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:32:24.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:24.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.362 seconds
[2025-04-06T10:32:54.950+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:54.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:32:54.968+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:32:54.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:55.370+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:32:55.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:32:55.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:32:55.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.637 seconds
[2025-04-06T10:33:26.124+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:26.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:33:26.153+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:33:26.153+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:26.409+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:33:26.407+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:33:26.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:26.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.528 seconds
[2025-04-06T10:33:57.124+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:57.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:33:57.141+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:33:57.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:58.317+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:33:58.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:33:58.322+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:33:58.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.390 seconds
[2025-04-06T10:34:28.827+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:28.832+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:34:28.838+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:34:28.837+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:29.023+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:34:29.020+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:34:29.024+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:29.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.263 seconds
[2025-04-06T10:34:59.132+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:59.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:34:59.140+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:34:59.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:59.349+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:34:59.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:34:59.351+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:34:59.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.347 seconds
[2025-04-06T10:35:29.986+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:35:29.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:35:30.005+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:35:30.004+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:35:30.423+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:35:30.420+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:35:30.426+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:35:30.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.648 seconds
[2025-04-06T10:36:00.938+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:00.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:36:00.948+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:36:00.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:01.142+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:36:01.140+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:36:01.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:01.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.260 seconds
[2025-04-06T10:36:31.378+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:31.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:36:31.393+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:36:31.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:31.811+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:36:31.808+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 10, in <module>
    from API_BCN import main as run_bcn
ImportError: cannot import name 'main' from 'API_BCN' (/opt/airflow/dags/../apis/API_BCN.py)
[2025-04-06T10:36:31.812+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:36:31.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.597 seconds
[2025-04-06T10:37:02.176+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:02.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:37:02.192+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:37:02.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:16.401+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:37:16.395+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:37:16.402+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:16.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 14.281 seconds
[2025-04-06T10:37:46.780+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:46.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:37:46.792+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:37:46.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:47.808+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:37:47.805+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:37:47.809+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:37:47.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.075 seconds
[2025-04-06T10:38:18.757+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:38:19.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:38:19.678+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:38:19.677+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:43:05.009+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:43:05.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:43:05.064+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:43:05.063+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:43:17.491+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:43:17.481+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:43:17.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:43:17.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 12.637 seconds
[2025-04-06T10:49:24.756+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:49:24.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:49:24.835+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:49:24.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:49:31.316+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:49:31.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:49:31.320+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:49:31.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 6.629 seconds
[2025-04-06T10:50:01.744+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:01.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:50:01.760+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:50:01.759+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:05.345+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:50:05.331+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:50:05.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:05.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.710 seconds
[2025-04-06T10:50:35.917+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:35.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:50:35.929+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:50:35.928+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:37.585+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:50:37.578+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:50:37.588+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:50:37.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.841 seconds
[2025-04-06T10:51:08.182+0000] {processor.py:157} INFO - Started process (PID=35) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:08.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:51:08.190+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:51:08.189+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:09.119+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:51:09.116+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:51:09.119+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:09.155+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.980 seconds
[2025-04-06T10:51:39.464+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:39.469+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:51:39.475+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:51:39.474+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:41.155+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:51:41.140+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:51:41.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:51:41.196+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.738 seconds
[2025-04-06T10:52:11.532+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:11.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:52:11.546+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:52:11.545+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:12.584+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:52:12.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:52:12.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:12.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.118 seconds
[2025-04-06T10:52:43.185+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:43.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:52:43.256+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:52:43.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:46.603+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:52:46.597+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:52:46.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:52:46.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.571 seconds
[2025-04-06T10:53:17.611+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:17.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:53:17.873+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:53:17.870+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:21.372+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:53:21.366+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:53:21.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:21.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.940 seconds
[2025-04-06T10:53:51.741+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:51.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:53:51.755+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:53:51.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:53.719+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:53:53.716+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:53:53.721+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:53:53.770+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.036 seconds
[2025-04-06T10:54:24.090+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:54:24.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:54:24.263+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:54:24.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:54:27.995+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:54:27.988+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:54:27.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:54:28.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 4.084 seconds
[2025-04-06T10:54:58.337+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:54:58.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:54:58.344+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:54:58.343+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:55:00.653+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:55:00.645+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:55:00.656+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:55:00.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.373 seconds
[2025-04-06T10:55:31.017+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:55:31.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:55:31.028+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:55:31.028+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:55:32.132+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:55:32.130+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:55:32.134+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:55:32.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.153 seconds
[2025-04-06T10:56:02.309+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:02.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:56:02.318+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:56:02.317+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:03.423+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:56:03.420+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:56:03.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:03.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.151 seconds
[2025-04-06T10:56:34.106+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:34.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:56:34.154+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:56:34.153+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:35.382+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:56:35.379+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:56:35.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:56:35.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.327 seconds
[2025-04-06T10:57:02.461+0000] {processor.py:157} INFO - Started process (PID=57) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:02.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:57:02.477+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:57:02.476+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:04.887+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:57:04.885+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:57:04.888+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:04.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.472 seconds
[2025-04-06T10:57:35.490+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:35.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:57:35.577+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:57:35.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:36.719+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:57:36.715+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:57:36.719+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:57:36.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.269 seconds
[2025-04-06T10:58:06.819+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:06.826+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:58:06.830+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:06.830+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:07.734+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:07.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:58:07.735+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:07.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 0.964 seconds
[2025-04-06T10:58:23.259+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:23.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:58:23.277+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:23.276+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:25.388+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:25.383+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:58:25.392+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:25.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.274 seconds
[2025-04-06T10:58:38.580+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:38.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:58:38.624+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:38.623+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:41.436+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:58:41.433+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:58:41.437+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:58:41.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.961 seconds
[2025-04-06T10:59:12.224+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:12.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:59:12.239+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:59:12.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:13.494+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:59:13.491+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:59:13.495+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:13.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.312 seconds
[2025-04-06T10:59:43.828+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:43.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T10:59:43.851+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:59:43.850+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:45.942+0000] {logging_mixin.py:151} INFO - [2025-04-06T10:59:45.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T10:59:45.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T10:59:45.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.164 seconds
[2025-04-06T11:00:16.226+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:16.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:00:16.244+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:00:16.243+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:17.550+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:00:17.546+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:00:17.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:17.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.365 seconds
[2025-04-06T11:00:47.992+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:48.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:00:48.012+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:00:48.008+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:49.367+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:00:49.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:00:49.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:00:49.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.450 seconds
[2025-04-06T11:01:19.885+0000] {processor.py:157} INFO - Started process (PID=75) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:19.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:01:19.894+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:01:19.893+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:21.264+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:01:21.261+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:01:21.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:21.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.426 seconds
[2025-04-06T11:01:51.651+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:51.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:01:51.685+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:01:51.685+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:53.153+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:01:53.147+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:01:53.155+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:01:53.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.572 seconds
[2025-04-06T11:02:23.556+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:23.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:02:23.566+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:02:23.565+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:24.513+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:02:24.510+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:02:24.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:24.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.002 seconds
[2025-04-06T11:02:54.936+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:54.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:02:54.958+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:02:54.958+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:56.320+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:02:56.316+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:02:56.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:02:56.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.431 seconds
[2025-04-06T11:03:26.745+0000] {processor.py:157} INFO - Started process (PID=83) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:26.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:03:26.757+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:03:26.756+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:28.056+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:03:28.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:03:28.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:28.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.353 seconds
[2025-04-06T11:03:58.453+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:58.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:03:58.469+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:03:58.468+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:59.777+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:03:59.775+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:03:59.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:03:59.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.370 seconds
[2025-04-06T11:04:30.211+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:04:30.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:04:30.232+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:04:30.231+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:04:31.703+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:04:31.700+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:04:31.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:04:31.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.544 seconds
[2025-04-06T11:05:02.279+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:02.289+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:05:02.296+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:05:02.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:03.995+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:05:03.989+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:05:03.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:04.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.763 seconds
[2025-04-06T11:05:34.370+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:34.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:05:34.389+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:05:34.389+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:35.664+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:05:35.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:05:35.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:05:35.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.331 seconds
[2025-04-06T11:06:06.178+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:06:06.187+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:06:06.193+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:06:06.193+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:06:07.442+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:06:07.431+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:06:07.448+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:06:07.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.324 seconds
[2025-04-06T11:06:38.252+0000] {processor.py:157} INFO - Started process (PID=95) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:06:38.268+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:06:38.275+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:06:38.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:08:24.381+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:08:24.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:08:24.446+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:08:24.445+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:08:40.254+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:08:40.228+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:08:40.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:08:40.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 16.071 seconds
[2025-04-06T11:09:10.594+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:10.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:09:10.631+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:09:10.629+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:14.086+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:09:14.081+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:09:14.088+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:14.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.573 seconds
[2025-04-06T11:09:44.613+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:44.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:09:44.649+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:09:44.648+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:48.060+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:09:48.055+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:09:48.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:09:48.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.566 seconds
[2025-04-06T11:10:18.410+0000] {processor.py:157} INFO - Started process (PID=35) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:18.423+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:10:18.432+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:10:18.431+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:19.806+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:10:19.801+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:10:19.808+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:19.851+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.465 seconds
[2025-04-06T11:10:50.421+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:50.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:10:50.442+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:10:50.441+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:54.892+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:10:54.888+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:10:54.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:10:54.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 4.562 seconds
[2025-04-06T11:11:25.204+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:11:25.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:11:25.230+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:11:25.228+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:11:27.959+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:11:27.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:11:27.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:11:28.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.826 seconds
[2025-04-06T11:11:58.670+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:11:58.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:11:58.697+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:11:58.696+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:12:01.415+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:12:01.411+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:12:01.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:12:01.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.838 seconds
[2025-04-06T11:12:31.873+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:12:32.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:12:32.050+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:12:32.049+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:12:39.061+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:12:39.055+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:12:39.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:12:39.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 7.804 seconds
[2025-04-06T11:13:10.043+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:13:10.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:13:10.059+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:13:10.058+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:13:11.815+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:13:11.803+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 11, in <module>
    from API_GM import main as run_gm
ImportError: cannot import name 'main' from 'API_GM' (/opt/airflow/dags/../apis/API_GM.py)
[2025-04-06T11:13:11.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:13:11.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.859 seconds
[2025-04-06T11:17:45.791+0000] {processor.py:157} INFO - Started process (PID=28) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:17:45.814+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:17:45.852+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:17:45.851+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:18:01.012+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:18:01.006+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:18:01.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:18:01.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 15.571 seconds
[2025-04-06T11:18:31.814+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:18:31.848+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:18:32.077+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:18:32.066+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:18:38.556+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:18:38.541+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:18:38.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:18:38.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 6.910 seconds
[2025-04-06T11:19:09.366+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:09.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:19:09.420+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:19:09.418+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:13.155+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:19:13.145+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:19:13.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:13.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 4.014 seconds
[2025-04-06T11:19:44.082+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:44.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:19:44.112+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:19:44.112+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:45.974+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:19:45.967+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:19:45.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:19:46.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.957 seconds
[2025-04-06T11:20:16.564+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:16.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:20:16.835+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:20:16.834+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:19.912+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:20:19.894+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:20:19.914+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:19.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.417 seconds
[2025-04-06T11:20:50.374+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:50.404+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:20:50.418+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:20:50.415+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:53.680+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:20:53.668+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:20:53.681+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:20:53.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 3.540 seconds
[2025-04-06T11:21:23.991+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:24.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:21:24.020+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:21:24.019+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:25.961+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:21:25.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:21:25.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:26.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 2.023 seconds
[2025-04-06T11:21:56.689+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:56.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:21:56.733+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:21:56.731+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:58.048+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:21:58.045+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:21:58.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:21:58.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.409 seconds
[2025-04-06T11:22:28.474+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:22:28.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:22:28.565+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:22:28.563+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:22:29.705+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:22:29.695+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:22:29.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:22:29.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.283 seconds
[2025-04-06T11:23:00.044+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:23:00.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/orchestator_dag.py for tasks to queue
[2025-04-06T11:23:00.060+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:23:00.059+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:23:01.839+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:23:01.835+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/orchestator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/orchestator_dag.py", line 28, in <module>
    task_bcn = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 794, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: run_API_BCN). Invalid arguments were:
**kwargs: {'schedule_interval': '@weekly'}
[2025-04-06T11:23:01.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/orchestator_dag.py
[2025-04-06T11:23:01.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/orchestator_dag.py took 1.843 seconds
